"""Storage protocol for the learning engine."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class MemoryBackend(Protocol):
    """Storage interface the learning engine requires.

    Implement this protocol with any backend (SQLite, Postgres, Redis, etc.)
    to use the learning engine.
    """

    # Knowledge CRUD
    def get_active_knowledge(self, user_id: str) -> list[dict]: ...
    def save_knowledge(self, user_id: str, category: str, subject: str,
                       content: str, **kwargs) -> int: ...
    def update_knowledge(self, knowledge_id: int, **kwargs) -> None: ...

    # Corrections
    def save_correction(self, user_id: str, knowledge_id: int,
                        old_content: str, new_content: str,
                        trigger_text: str) -> int: ...
    def get_corrections(self, user_id: str, limit: int = 10) -> list[dict]: ...

    # Teachings
    def save_teaching(self, user_id: str, trigger_pattern: str,
                      response_guidance: str, category: str) -> int: ...
    def get_teachings(self, user_id: str, active_only: bool = True) -> list[dict]: ...
    def increment_teaching_usage(self, teaching_id: int) -> None: ...
    def deactivate_teaching(self, teaching_id: int) -> None: ...

    # Documents
    def save_document_chunk(self, user_id: str, source_name: str,
                            source_type: str, chunk_index: int, text: str) -> None: ...
    def delete_document(self, user_id: str, source_name: str) -> None: ...
    def list_documents(self, user_id: str) -> list[dict]: ...

    # Failures
    def save_failure(self, user_id: str, skill_name: str,
                     input_json: str, error_message: str) -> int: ...
    def get_recent_failures(self, user_id: str, limit: int = 20) -> list[dict]: ...

    # Behavioral patterns
    def get_behavioral_patterns(self, user_id: str,
                                min_confidence: float = 0.5) -> list[dict]: ...
